### ISSUE TITLE
error in ha 2023.3.0 with python 3.11

### ISSUE THREAD

**Issue by bbr111** [jeroenterheerdt/HADailySensor#35]
2023-03-02 21:39:22.334 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.daily.sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/homeassistant/.homeassistant/custom_components/daily/sensor.py", line 40, in <module>
class DailySensor(DailySensorEntity):
File "/home/homeassistant/.homeassistant/custom_components/daily/sensor.py", line 49, in DailySensor
@asyncio.coroutine
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
2023-03-02 21:39:22.344 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform daily.sensor: Platform not found (Exception importing custom_components.daily.sensor).
2023-03-02 21:39:22.349 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.daily.sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/homeassistant/.homeassistant/custom_components/daily/sensor.py", line 40, in <module>
class DailySensor(DailySensorEntity):
File "/home/homeassistant/.homeassistant/custom_components/daily/sensor.py", line 49, in DailySensor
@asyncio.coroutine
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
2023-03-02 21:39:22.355 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform daily.sensor: Platform not found (Exception importing custom_components.daily.sensor).
2023-03-02 21:39:22.358 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.daily.sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/homeassistant/.homeassistant/custom_components/daily/sensor.py", line 40, in <module>
class DailySensor(DailySensorEntity):
File "/home/homeassistant/.homeassistant/custom_components/daily/sensor.py", line 49, in DailySensor
@asyncio.coroutine
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
2023-03-02 21:39:22.364 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform daily.sensor: Platform not found (Exception importing custom_components.daily.sensor).

**Comment by jeroenterheerdt** [comment]
https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v0.4.0
