### ISSUE TITLE
No data HA2023.6 beta

### ISSUE THREAD

**Issue by tomg1970** [jeroenterheerdt/HADailySensor#39]
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/daily/sensor.py:49 
Integration: Daily Sensor (documentation, issues) 
First occurred: 08:51:06 (5 occurrences) 
Last logged: 08:51:06

Unexpected exception importing platform custom_components.daily.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daily/sensor.py", line 40, in <module>
    class DailySensor(DailySensorEntity):
  File "/config/custom_components/daily/sensor.py", line 49, in DailySensor
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
`

**Comment by Kaibob2** [comment]
```
Logger: homeassistant.loader
Source: custom_components/daily/sensor.py:49
Integration: Daily Sensor ([documentation](https://github.com/jeroenterheerdt/HADailySensor), [issues](https://github.com/jeroenterheerdt/HADailySensor/issues))
First occurred: 23:04:12 (5 occurrences)
Last logged: 23:04:12
Unexpected exception importing platform custom_components.daily.sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daily/sensor.py", line 40, in <module>
    class DailySensor(DailySensorEntity):
  File "/config/custom_components/daily/sensor.py", line 49, in DailySensor
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

```
 Logger: homeassistant.setup
Source: setup.py:374
First occurred: 23:04:12 (5 occurrences)
Last logged: 23:04:12
Unable to prepare setup for platform daily.sensor: Platform not found (Exception importing custom_components.daily.sensor).
```

**Comment by olealm** [comment]
Same issue.

**Comment by XtremeLead** [comment]
Same here after updating to Home Assistant Core 2023.6.0.

**Comment by marcel-sch** [comment]
> edit: Just checked...#36 fixes this issue.

it works for me too, thanks for the PR @bbr111

**Comment by kwithus** [comment]
> @XtremeLead
> 
> THX - just uncomment/delete: **@asyncio.coroutine** in sensor.py line 49.

Yes, works for me too, thanks
Still, hopefully we will see an update soon

**Comment by sidwin9** [comment]
Hey,
Same problem with HAS 2023.6.0

**Comment by kwithus** [comment]
> Hey,
> Same problem with HAS 2023.6.0

As written bevor, you can edit the integration and solve it

go to 
/config/custom_components/daily/sensor.py

and delete the line 49

Then restart HA, 
Everything works

**Comment by Kaibob2** [comment]
Uncommenting line 49 in sensor.py works.
Issue fixed, thanks.

**Comment by vantop77** [comment]
Commenting line 49 (which means disabling code on that line, not uncommenting) fixes the problem also at my side.
