### ISSUE TITLE
None of the daily sensors is updating any more

### ISSUE THREAD

**Issue by JBecker32** [jeroenterheerdt/HADailySensor#56]
Since I made updates yesterday to the HADailySensor and Home assistant core (2024.6.0?), none of the daily sensors is updateing anymore. Instead I get the following in the log file
2024-06-07 09:49:38.169 INFO (MainThread) [custom_components.daily] Updating Daily Sensor HoymilesMaxofDaykWh
2024-06-07 09:49:38.174 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daily/sensor.py", line 72, in <lambda>
    lambda event: self._handle_update(  # pylint: disable=unnecessary-lambda
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daily/sensor.py", line 102, in _handle_update
    the_val = self.convert_to_float(input_state)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daily/sensor.py", line 155, in convert_to_float
    return float(float_value)
           ^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'State'

Any clue to what has happened?
BR, Jörg.

**Comment by JBecker32** [comment]
I have just noticed that the same error has already been reported in a recation to fix #52. So this seems to be a problem with HADailySensor, not with core 2024.6.0 !?!

**Comment by Tntdruid** [comment]
Same for me.

**Comment by Giorsetti** [comment]
Same for me...

**Comment by cobraviola** [comment]
Same for me...

**Comment by jeroenterheerdt** [comment]
Which version of daily are you all using? At least including that would make the 'same for me' kind of useful...

**Comment by cobraviola** [comment]
2024.4.4

**Comment by JBecker32** [comment]
Updated yesterday, so the latest version ...

**Comment by Giorsetti** [comment]
2024.4.4

**Comment by Janorei** [comment]
I've got the same Problem after updating the Daily Sensors

TypeError: float() argument must be a string or a real number, not 'State'
2024-06-07 19:46:12.409 ERROR (SyncWorker_4) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daily/sensor.py", line 72, in <lambda>
    lambda event: self._handle_update(
                ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daily/sensor.py", line 102, in _handle_update
    the_val = self.convert_to_float(input_state)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daily/sensor.py", line 155, in convert_to_float
    return float(float_value)
           ^^^^^^^^^^^^^^^^^^

**Comment by 314159265358979323-h** [comment]
Same for me 2025.4.4

**Comment by Giorsetti** [comment]
Thank you and have a nice day.

 

De : Jeroen ter Heerdt ***@***.***> 
Envoyé : samedi 8 juin 2024 01:23
À : jeroenterheerdt/HADailySensor ***@***.***>
Cc : Giorsetti ***@***.***>; Comment ***@***.***>
Objet : Re: [jeroenterheerdt/HADailySensor] None of the daily sensors is updating any more (Issue #56)

 

Closed #56 <https://github.com/jeroenterheerdt/HADailySensor/issues/56>  as completed via  <https://github.com/jeroenterheerdt/HADailySensor/commit/5bb812b2b189ee5cd4e3292e95c8accf46861c0f> 5bb812b.

**Comment by JBecker32** [comment]
Perfect fix, thank you, Jeroen!

**Comment by Tntdruid** [comment]
Thanks for the fix.

**Comment by cobraviola** [comment]
Tank for the fix
