### ISSUE TITLE
HA Crash

### ISSUE THREAD

**Issue by Tntdruid** [jeroenterheerdt/HADailySensor#74]
When i edit any of the daily sesnsor Ha crash every time, is that a new bug?

**Comment by Tntdruid** [comment]
160 mb log file whit this:

ValueError: Config entry Min Jord Fugt (01J44W1PMAWH6FN2W4YF1T9BFX) for daily.sensor has already been setup!
2024-10-24 10:47:12.387 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Min Jord Fugt for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError(
ValueError: Config entry Min Jord Fugt (01J44W1PMAWH6FN2W4YF1T9BFX) for daily.sensor has already been setup!

**Comment by Jajjaman** [comment]
Same problem here.

**Comment by jeroenterheerdt** [comment]
I am afraid I don't know how to fix this :(

**Comment by Tntdruid** [comment]
If i delete and recreated it works.

**Comment by Vladx71** [comment]
Same here with a simple rename operation....

ValueError: Config entry Gázfogyasztás (Wh) (01JCB26PYRGZB6HEGR104M08JQ) for daily.sensor has already been setup!
2024-11-16 09:22:37.953 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Gázfogyasztás (Wh) for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 133, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 186, in async_setup_entry
    raise ValueError(
ValueError: Config entry Gázfogyasztás (Wh) (01JCB26PYRGZB6HEGR104M08JQ) for daily.sensor has already been setup!
2024-11-16 09:22:37.957 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Gázfogyasztás (Wh) for sensor

**Comment by OlofBailey** [comment]
I have the same issue

**Comment by Reinqusito** [comment]
Same issue (v 2024.10.1).
_Core 2025.1.2
Supervisor 2024.12.3
Operating System 14.1
Frontend 20250109.0_

**Comment by stovedoctor** [comment]
Yup HA restarts when you exit the sensor or name

**Comment by lievendf** [comment]
Same here, simply tried to rename a sensor...

**Comment by qvqn** [comment]
same issue if you try to edit and save it crashes i updated interval and ha will die

**Comment by lullatscho** [comment]
> I am afraid I don't know how to fix this :(

When editing an existing sensor (e.g., changing the source or aggregation method) in Home Assistant, the system crashes with the following error:

_ValueError: Config entry ... has already been setup!_

This patch modifies async_setup_entry to check if the config entry already exists and, instead of raising an exception, updates the existing sensor’s configuration dynamically.

This allows users to edit sensors without causing Home Assistant to fail during startup or reload.

Patch file attached below.

**Comment by jeroenterheerdt** [comment]
Awesome! Is there any chance you can make a PR?

**Comment by lullatscho** [comment]
> Awesome! Is there any chance you can make a PR? 

PR is available for review by you

**Comment by jeroenterheerdt** [comment]
> > Awesome! Is there any chance you can make a PR?
> 
> PR is available for review by you

thanks, but as mentioned in the PR this does not resolve anything.

**Comment by lullatscho** [comment]
> > > Awesome! Is there any chance you can make a PR?
> > 
> > 
> > PR is available for review by you
> 
> thanks, but as mentioned in the PR this does not resolve anything, at least not on my machine. What are you seeing?

Hey,

I'm really sorry for submitting a pull request without thoroughly testing it first. I know it ended up causing issues and extra work on your end. I'll make sure to be more careful with testing in the future. Thanks a lot for your patience and all the hard work you put into the project.

I just wanted to let you know that I've submitted a new pull request. In this version, Home Assistant no longer crashes when changing the interval, and you can now update the interval for existing sensors on the fly.

**Comment by jeroenterheerdt** [comment]
Thanks, I'll test it. I think we should also add support for updates to unit of measurement and other config options.
